button_color = "black"
button_hover_color = "#404040"
text_color = "white"

[bar]
height = 32
font = "/usr/share/ppkui/panel.ttf"

[[bar.buttons]]
text = "A"
command = "swaymsg kill"

[[bar.buttons]]
text = "B"
command = "swaymsg focus prev"

[[bar.buttons]]
text = "C"
command = "j4-dmenu-desktop --dmenu='ppkui_menu --config '/etc/ppkui/bar.toml --term='xterm'"

[[bar.buttons]]
text = "D"
command = "swaymsg focus next"

[[bar.buttons]]
# TODO
text = "E"
command = "urxvt -e sh -c 'env; read'"

[launcher]
line_height = 32
max_lines = 8
font = "/usr/share/fonts/noto/NotoSans-Regular.ttf"
